"""Layered, strongly-typed configuration.

Resolution order, later layers overriding earlier ones:

1. Field defaults declared on the models in this module.
2. Every ``*.yaml`` in the config directory (``app``, ``logging``, ``models``,
   ``thresholds``), deep-merged in that order.
3. ``app.<environment>.yaml`` if present, giving per-environment overlays.
4. A ``.env`` file, if one exists next to the repository root.
5. Process environment variables prefixed ``HQ_``, with ``__`` denoting
   nesting (``HQ_SERVER__PORT`` -> ``server.port``).

The config directory is ``$HQ_CONFIG_DIR`` when set, otherwise ``<repo>/configs``.

Every threshold that can change an accept/reject outcome is reachable from
:class:`Settings`; none is hard-coded elsewhere in the codebase.
"""

from __future__ import annotations

import json
import os
import socket
import tempfile
import threading
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Annotated, Any, Literal

import yaml
from pydantic import (
    BaseModel,
    Field,
    ValidationError,
    computed_field,
    field_validator,
    model_validator,
)
from pydantic_settings import (
    BaseSettings,
    NoDecode,
    PydanticBaseSettingsSource,
    SettingsConfigDict,
)

from hamqadam_ai.core.exceptions import ConfigurationError

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #

#: Repository root: src/hamqadam_ai/core/config.py -> up four levels.
REPO_ROOT: Path = Path(__file__).resolve().parents[3]

#: YAML files merged, in order, to form the base configuration.
#: ``model_digests.lock.yaml`` is generated by ``scripts/download_models.py``
#: and merged *after* ``models.yaml`` so the pinned SHA-256 digests it records
#: override the ``null`` placeholders in the declaration file.
_CONFIG_FILE_ORDER: tuple[str, ...] = (
    "app.yaml",
    "logging.yaml",
    "models.yaml",
    "model_digests.lock.yaml",
    "thresholds.yaml",
)

DeviceLiteral = Literal["auto", "cpu", "cuda", "tensorrt", "directml", "coreml"]
EnvironmentLiteral = Literal["development", "testing", "staging", "production"]
LogLevelLiteral = Literal["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]


def _deep_merge(base: dict[str, Any], overlay: Mapping[str, Any]) -> dict[str, Any]:
    """Recursively merge ``overlay`` into ``base``, returning a new dict.

    Mappings merge key-by-key; every other type (including lists) is replaced
    wholesale. Replacing lists rather than concatenating them is deliberate:
    an operator overriding ``fallback_chain`` means "use exactly this chain".
    """
    merged = dict(base)
    for key, value in overlay.items():
        existing = merged.get(key)
        if isinstance(existing, dict) and isinstance(value, Mapping):
            merged[key] = _deep_merge(existing, value)
        else:
            merged[key] = value
    return merged


def resolve_config_dir() -> Path:
    """Return the directory holding the YAML configuration files."""
    override = os.environ.get("HQ_CONFIG_DIR")
    if override:
        path = Path(override).expanduser().resolve()
        if not path.is_dir():
            raise ConfigurationError(
                f"HQ_CONFIG_DIR points at {path} which is not a directory.",
                details={"config_dir": str(path)},
            )
        return path
    return REPO_ROOT / "configs"


class _YamlSettingsSource(PydanticBaseSettingsSource):
    """Settings source that deep-merges the project's YAML configuration."""

    def __init__(self, settings_cls: type[BaseSettings]) -> None:
        super().__init__(settings_cls)
        self._data: dict[str, Any] = self._load()

    def _load(self) -> dict[str, Any]:
        config_dir = resolve_config_dir()
        merged: dict[str, Any] = {}

        for filename in _CONFIG_FILE_ORDER:
            path = config_dir / filename
            if not path.is_file():
                continue
            merged = _deep_merge(merged, _read_yaml(path))

        # Environment overlay. The environment name itself may come from the
        # process environment, so it is read directly rather than from the
        # partially-built settings object.
        environment = (
            os.environ.get("HQ_APP__ENVIRONMENT")
            or str(merged.get("app", {}).get("environment", "development"))
        ).strip().lower()

        overlay = config_dir / f"app.{environment}.yaml"
        if overlay.is_file():
            merged = _deep_merge(merged, _read_yaml(overlay))

        merged["_config_dir"] = str(config_dir)
        return merged

    def get_field_value(  # pragma: no cover - required by the ABC
        self,
        field: Any,  # noqa: ARG002 - part of the PydanticBaseSettingsSource contract
        field_name: str,
    ) -> tuple[Any, str, bool]:
        return self._data.get(field_name), field_name, False

    def __call__(self) -> dict[str, Any]:
        return self._data


def _read_yaml(path: Path) -> dict[str, Any]:
    """Parse a YAML document, raising a typed error on malformed content."""
    try:
        with path.open("r", encoding="utf-8") as handle:
            loaded = yaml.safe_load(handle)
    except yaml.YAMLError as exc:
        raise ConfigurationError(
            f"Configuration file {path.name} is not valid YAML.",
            details={"path": str(path), "reason": str(exc)},
            cause=exc,
        ) from exc
    if loaded is None:
        return {}
    if not isinstance(loaded, dict):
        raise ConfigurationError(
            f"Configuration file {path.name} must contain a mapping at the top level.",
            details={"path": str(path), "top_level_type": type(loaded).__name__},
        )
    return loaded


# --------------------------------------------------------------------------- #
# Application / transport
# --------------------------------------------------------------------------- #


class AppConfig(BaseModel):
    """Identity and lifecycle metadata for this deployment."""

    name: str = "hamqadam-ai-verification"
    version: str = "1.0.0"
    environment: EnvironmentLiteral = "development"
    debug: bool = False
    instance_id: str | None = None

    @property
    def is_production(self) -> bool:
        """True when running under the production profile."""
        return self.environment == "production"

    @model_validator(mode="after")
    def _default_instance_id(self) -> AppConfig:
        if self.instance_id is None:
            object.__setattr__(self, "instance_id", socket.gethostname())
        return self


class CorsConfig(BaseModel):
    """Cross-origin policy for the HTTP surface."""

    enabled: bool = True
    allow_origins: list[str] = Field(default_factory=list)
    allow_credentials: bool = False
    allow_methods: list[str] = Field(default_factory=lambda: ["GET", "POST"])
    allow_headers: list[str] = Field(default_factory=lambda: ["*"])


class ServerConfig(BaseModel):
    """Uvicorn / ASGI transport settings."""

    host: str = "0.0.0.0"
    port: int = Field(default=8000, ge=1, le=65535)
    workers: int = Field(default=1, ge=1, le=64)
    root_path: str = ""
    request_timeout_seconds: float = Field(default=45.0, gt=0, le=600)
    max_request_bytes: int = Field(default=40 * 1024 * 1024, gt=0)
    cors: CorsConfig = Field(default_factory=CorsConfig)


class HmacConfig(BaseModel):
    """Optional HMAC request-signing, layered on top of the API key."""

    enabled: bool = False
    header: str = "X-Signature"
    timestamp_header: str = "X-Timestamp"
    secret: str | None = None
    max_clock_skew_seconds: int = Field(default=300, gt=0)

    @model_validator(mode="after")
    def _secret_required_when_enabled(self) -> HmacConfig:
        if self.enabled and not self.secret:
            raise ValueError("security.hmac.secret must be set when HMAC signing is enabled")
        return self


class RateLimitConfig(BaseModel):
    """Token-bucket rate limiting, per API key."""

    enabled: bool = True
    requests_per_minute: int = Field(default=120, gt=0)
    burst: int = Field(default=30, gt=0)
    analyze_requests_per_minute: int = Field(default=40, gt=0)


class SecurityConfig(BaseModel):
    """Authentication, authorisation and abuse controls."""

    api_key_header: str = "X-API-Key"
    api_keys: Annotated[list[str], NoDecode] = Field(default_factory=list)
    require_api_key: bool = True
    hmac: HmacConfig = Field(default_factory=HmacConfig)
    rate_limit: RateLimitConfig = Field(default_factory=RateLimitConfig)
    enforce_production_hardening: bool = True

    @field_validator("api_keys", mode="before")
    @classmethod
    def _split_csv(cls, value: Any) -> Any:
        """Accept a comma-separated string so ``HQ_SECURITY__API_KEYS`` works.

        ``NoDecode`` on the annotation is what makes this reachable from the
        environment. Without it pydantic-settings classifies ``list[str]`` as a
        complex field and calls ``json.loads`` inside the *source*, so::

            HQ_SECURITY__API_KEYS=my-secret-key

        failed with ``SettingsError: error parsing value for field "security"``
        before this validator ran - an error naming the whole section rather
        than the field, and mentioning nothing about the real requirement, which
        was JSON. Environment variables are strings and an operator setting one
        key will write it plainly, so refusing that is a trap laid squarely in
        the deployment path.

        A JSON array is still accepted, since it arrives here as a string that
        happens to start with ``[``.
        """
        if isinstance(value, str):
            text = value.strip()
            if text.startswith("["):
                try:
                    parsed = json.loads(text)
                except ValueError as exc:
                    raise ValueError(
                        "security.api_keys looks like a JSON array but is not "
                        "valid JSON. Use a comma-separated list instead, or fix "
                        "the quoting."
                    ) from exc
                if not isinstance(parsed, list):
                    raise ValueError("security.api_keys must be a list of keys.")
                return [str(item).strip() for item in parsed if str(item).strip()]
            return [item.strip() for item in text.split(",") if item.strip()]
        return value


class StorageConfig(BaseModel):
    """Scratch storage policy. No user image is ever written durably."""

    temp_dir: Path | None = None
    temp_ttl_seconds: int = Field(default=300, gt=0)
    janitor_interval_seconds: int = Field(default=60, gt=0)
    secure_delete: bool = True
    model_dir: Path = Path("./model_store")

    @computed_field  # type: ignore[prop-decorator]
    @property
    def resolved_model_dir(self) -> Path:
        """Absolute path to the model store, relative to the repo root."""
        path = self.model_dir.expanduser()
        return path if path.is_absolute() else (REPO_ROOT / path).resolve()

    @computed_field  # type: ignore[prop-decorator]
    @property
    def resolved_temp_dir(self) -> Path:
        """Absolute path to the scratch root, defaulting to the system temp."""
        if self.temp_dir is not None:
            path = self.temp_dir.expanduser()
            return path if path.is_absolute() else (REPO_ROOT / path).resolve()
        return Path(tempfile.gettempdir()) / "hamqadam-ai"


class RuntimeConfig(BaseModel):
    """Hardware selection and ONNX Runtime tuning."""

    device: DeviceLiteral = "auto"
    gpu_device_id: int = Field(default=0, ge=0)
    intra_op_threads: int = Field(default=0, ge=0)
    inter_op_threads: int = Field(default=1, ge=0)

    graph_optimization_level: Literal["disable_all", "basic", "extended", "all"] = "all"
    warmup_on_startup: bool = True
    warmup_iterations: int = Field(default=2, ge=0, le=20)
    inference_workers: int = Field(default=4, ge=1, le=64)
    max_batch_size: int = Field(default=8, ge=1, le=128)


# --------------------------------------------------------------------------- #
# Observability
# --------------------------------------------------------------------------- #


class MetricsConfig(BaseModel):
    """Prometheus exposition settings."""

    enabled: bool = True
    path: str = "/metrics"
    latency_buckets: list[float] = Field(
        default_factory=lambda: [0.05, 0.1, 0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0, 21.0]
    )


class TracingConfig(BaseModel):
    """OpenTelemetry export settings."""

    enabled: bool = False
    otlp_endpoint: str | None = None
    sample_ratio: float = Field(default=0.05, ge=0.0, le=1.0)


class MLflowConfig(BaseModel):
    """MLflow tracking for model versions and evaluation runs."""

    enabled: bool = False
    tracking_uri: str | None = None
    experiment: str = "hamqadam-ai-verification"


class HealthConfig(BaseModel):
    """Readiness / liveness behaviour."""

    startup_grace_seconds: int = Field(default=120, gt=0)


class ObservabilityConfig(BaseModel):
    """Metrics, tracing, experiment tracking and health checks."""

    metrics: MetricsConfig = Field(default_factory=MetricsConfig)
    tracing: TracingConfig = Field(default_factory=TracingConfig)
    mlflow: MLflowConfig = Field(default_factory=MLflowConfig)
    health: HealthConfig = Field(default_factory=HealthConfig)


# --------------------------------------------------------------------------- #
# Logging
# --------------------------------------------------------------------------- #


class RedactionPattern(BaseModel):
    """A named regex applied to string values before serialisation."""

    name: str
    regex: str
    replacement: str = "[REDACTED]"


class RedactionConfig(BaseModel):
    """PII scrubbing applied to every log event."""

    enabled: bool = True
    drop_keys: list[str] = Field(default_factory=list)
    mask_keys: list[str] = Field(default_factory=list)
    mask: str = "[REDACTED]"
    patterns: list[RedactionPattern] = Field(default_factory=list)


class AccessLogConfig(BaseModel):
    """Audit trail of who called what, with no payload content."""

    enabled: bool = True
    logger_name: str = "hamqadam.access"
    include_headers: list[str] = Field(
        default_factory=lambda: ["user-agent", "x-request-id", "x-forwarded-for"]
    )


class LoggingConfig(BaseModel):
    """Structured logging configuration."""

    level: LogLevelLiteral = "INFO"
    renderer: Literal["json", "console"] = "json"
    timestamp_format: Literal["iso", "unix"] = "iso"
    utc: bool = True
    include_call_site_from: LogLevelLiteral = "WARNING"
    levels: dict[str, LogLevelLiteral] = Field(default_factory=dict)
    redaction: RedactionConfig = Field(default_factory=RedactionConfig)
    access_log: AccessLogConfig = Field(default_factory=AccessLogConfig)


# --------------------------------------------------------------------------- #
# Model registry
# --------------------------------------------------------------------------- #


class ModelSourceSpec(BaseModel):
    """Where a model artefact is fetched from."""

    type: Literal["insightface_pack", "url", "multi_url", "bundled", "manual"] = "manual"
    url: str | None = None
    urls: list[dict[str, str]] = Field(default_factory=list)
    pack: str | None = None
    member: str | None = None


class ModelInputSpec(BaseModel):
    """Pre-processing contract for a model's input tensor."""

    size: tuple[int, int] = (640, 640)
    mean: float | list[float] = 0.0
    scale: float = 1.0
    swap_rb: bool = True
    letterbox: bool = False

    @property
    def mean_tuple(self) -> tuple[float, float, float]:
        """Per-channel mean, broadcasting a scalar across all three channels."""
        if isinstance(self.mean, int | float):
            value = float(self.mean)
            return (value, value, value)
        if len(self.mean) != 3:
            raise ValueError("input.mean must be a scalar or a 3-element list")
        return (float(self.mean[0]), float(self.mean[1]), float(self.mean[2]))


class ModelRuntimeSpec(BaseModel):
    """How the runtime may schedule work against this model."""

    dynamic_input: bool = True
    batch_capable: bool = False
    max_batch: int = Field(default=1, ge=1)


class ModelSpec(BaseModel):
    """A single versioned, integrity-checked model artefact."""

    enabled: bool = True
    required: bool = False
    kind: Literal["onnx", "caffe", "haar_cascade", "paddle", "torch"] = "onnx"
    version: str
    path: str
    config_path: str | None = None
    eye_cascade_path: str | None = None
    sha256: str | None = None
    source: ModelSourceSpec = Field(default_factory=ModelSourceSpec)
    input: ModelInputSpec = Field(default_factory=ModelInputSpec)
    output: dict[str, Any] = Field(default_factory=dict)
    runtime: ModelRuntimeSpec = Field(default_factory=ModelRuntimeSpec)

    model_config = {"protected_namespaces": ()}


class ModelStoreConfig(BaseModel):
    """Global policy for the on-disk model store."""

    root: Path = Path("./model_store")
    verify_checksum: bool = True
    download_timeout_seconds: int = Field(default=600, gt=0)
    insightface_pack_url: str = (
        "https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip"
    )

    model_config = {"protected_namespaces": ()}


class ProviderSpec(BaseModel):
    """An ONNX Runtime execution provider and its options."""

    name: str
    options: dict[str, Any] = Field(default_factory=dict)


# --------------------------------------------------------------------------- #
# MODULE 1 - detection thresholds
# --------------------------------------------------------------------------- #


class DetectionPolicyConfig(BaseModel):
    """Rules that turn raw detections into an accept / reject verdict."""

    min_confidence: float = Field(default=0.60, ge=0.0, le=1.0)
    min_face_area_ratio: float = Field(default=0.008, ge=0.0, le=1.0)
    max_face_area_ratio: float = Field(default=0.95, gt=0.0, le=1.0)
    min_face_pixels: int = Field(default=64, ge=16)
    max_faces_allowed: int = Field(default=1, ge=1)
    bystander_area_ratio: float = Field(default=0.35, ge=0.0, le=1.0)
    on_multiple_faces: Literal["reject", "select_primary"] = "reject"
    max_truncation_ratio: float = Field(default=0.10, ge=0.0, le=1.0)

    @model_validator(mode="after")
    def _area_bounds_ordered(self) -> DetectionPolicyConfig:
        if self.min_face_area_ratio >= self.max_face_area_ratio:
            raise ValueError(
                "detection.policy.min_face_area_ratio must be < max_face_area_ratio"
            )
        return self


class PoseConfig(BaseModel):
    """Head-orientation tolerances, in degrees of absolute deviation."""

    max_yaw: float = Field(default=30.0, gt=0, le=90)
    max_pitch: float = Field(default=25.0, gt=0, le=90)
    max_roll: float = Field(default=25.0, gt=0, le=90)
    hard_max_yaw: float = Field(default=50.0, gt=0, le=90)
    hard_max_pitch: float = Field(default=45.0, gt=0, le=90)
    hard_max_roll: float = Field(default=45.0, gt=0, le=90)
    visibility_weight: float = Field(default=0.25, ge=0.0, le=1.0)

    @model_validator(mode="after")
    def _soft_below_hard(self) -> PoseConfig:
        for axis in ("yaw", "pitch", "roll"):
            soft = getattr(self, f"max_{axis}")
            hard = getattr(self, f"hard_max_{axis}")
            if soft > hard:
                raise ValueError(f"detection.pose.max_{axis} must be <= hard_max_{axis}")
        return self


class OcclusionConfig(BaseModel):
    """Occlusion analyser thresholds and per-region importance weights."""

    region_threshold: float = Field(default=0.55, ge=0.0, le=1.0)
    overall_threshold: float = Field(default=0.45, ge=0.0, le=1.0)
    region_weights: dict[str, float] = Field(
        default_factory=lambda: {
            "forehead": 0.10,
            "left_eye": 0.22,
            "right_eye": 0.22,
            "nose": 0.18,
            "mouth": 0.16,
            "chin": 0.12,
        }
    )
    texture_energy_floor: float = Field(default=0.35, ge=0.0, le=1.0)
    skin_coverage_floor: float = Field(default=0.30, ge=0.0, le=1.0)
    symmetry_delta_threshold: float = Field(default=0.35, ge=0.0, le=1.0)
    visibility_weight: float = Field(default=0.35, ge=0.0, le=1.0)

    @model_validator(mode="after")
    def _weights_normalised(self) -> OcclusionConfig:
        total = sum(self.region_weights.values())
        if total <= 0:
            raise ValueError("detection.occlusion.region_weights must sum to a positive value")
        if abs(total - 1.0) > 1e-6:
            # Normalise rather than reject: an operator tuning one region up
            # should not have to rebalance the other five by hand.
            object.__setattr__(
                self,
                "region_weights",
                {key: value / total for key, value in self.region_weights.items()},
            )
        return self


class VisibilityConfig(BaseModel):
    """Weights of the composite face-visibility score."""

    weights: dict[str, float] = Field(
        default_factory=lambda: {
            "detector_confidence": 0.20,
            "occlusion": 0.30,
            "pose": 0.22,
            "face_size": 0.16,
            "framing": 0.12,
        }
    )
    min_acceptable: float = Field(default=0.55, ge=0.0, le=1.0)

    _REQUIRED_KEYS = ("detector_confidence", "occlusion", "pose", "face_size", "framing")

    @model_validator(mode="after")
    def _validate_weights(self) -> VisibilityConfig:
        missing = [key for key in self._REQUIRED_KEYS if key not in self.weights]
        if missing:
            raise ValueError(f"detection.visibility.weights is missing keys: {missing}")
        total = sum(self.weights.values())
        if total <= 0:
            raise ValueError("detection.visibility.weights must sum to a positive value")
        if abs(total - 1.0) > 1e-6:
            object.__setattr__(
                self,
                "weights",
                {key: value / total for key, value in self.weights.items()},
            )
        return self


class DetectionConfig(BaseModel):
    """MODULE 1 - face detection configuration."""

    primary: str = "scrfd"
    fallback_chain: list[str] = Field(
        default_factory=lambda: ["scrfd", "yolo", "opencv_dnn", "haar"]
    )
    max_fallback_depth: int = Field(default=4, ge=1)

    score_threshold: float = Field(default=0.50, ge=0.0, le=1.0)
    nms_iou_threshold: float = Field(default=0.40, ge=0.0, le=1.0)
    max_candidates: int = Field(default=200, ge=1)

    detection_input_size: tuple[int, int] = (640, 640)
    max_source_long_side: int = Field(default=1920, ge=256)
    min_source_short_side: int = Field(default=160, ge=32)

    policy: DetectionPolicyConfig = Field(default_factory=DetectionPolicyConfig)
    pose: PoseConfig = Field(default_factory=PoseConfig)
    occlusion: OcclusionConfig = Field(default_factory=OcclusionConfig)
    visibility: VisibilityConfig = Field(default_factory=VisibilityConfig)

    @model_validator(mode="after")
    def _primary_in_chain(self) -> DetectionConfig:
        if self.primary not in self.fallback_chain:
            object.__setattr__(
                self, "fallback_chain", [self.primary, *self.fallback_chain]
            )
        return self

    @field_validator("detection_input_size")
    @classmethod
    def _input_size_divisible(cls, value: tuple[int, int]) -> tuple[int, int]:
        """SCRFD's largest stride is 32; the input must tile it exactly."""
        width, height = value
        if width % 32 or height % 32:
            raise ValueError("detection.detection_input_size must be a multiple of 32")
        return value


# --------------------------------------------------------------------------- #
# Thresholds for modules delivered later. Declared now so the config file is
# complete and validated from day one.
# --------------------------------------------------------------------------- #


def _normalised_weights(weights: dict[str, float], label: str) -> dict[str, float]:
    """Rescale a weight mapping to sum to 1.0.

    Normalising rather than rejecting means an operator can raise one weight
    without having to rebalance every other by hand - the single most common
    way a hand-edited threshold file ends up subtly wrong.
    """
    total = sum(weights.values())
    if total <= 0:
        raise ValueError(f"{label} weights must sum to a positive value")
    if abs(total - 1.0) <= 1e-6:
        return weights
    return {key: value / total for key, value in weights.items()}


class RampMapping(BaseModel):
    """Maps a raw measurement onto ``[0, 1]`` through two anchor points.

    ``floor`` scores 0 and ``good`` scores 1, with a smoothstep in between.
    A smoothstep rather than a straight line because the derivative vanishes at
    both anchors, so a measurement sitting near an anchor does not swing the
    composite score on sensor noise alone.

    When ``floor > good`` the metric is lower-is-better - noise sigma, JPEG
    blockiness, chromatic aberration - and the ramp inverts automatically.

    ``log_scale`` interpolates in log10 space instead. This is not a cosmetic
    choice: the focus measures span three orders of magnitude between a sharp
    photograph and an unusable one (measured Laplacian variance runs 37 to
    10,014 on the same portrait), and a linear ramp across that range spends
    almost its entire output on the top decade while collapsing everything
    below it to zero. Perceptually and statistically these quantities are
    log-distributed, so the ramp should be too.
    """

    floor: float
    good: float
    log_scale: bool = False

    @property
    def lower_is_better(self) -> bool:
        """True when a smaller raw value scores higher."""
        return self.floor > self.good

    @model_validator(mode="after")
    def _anchors_valid(self) -> RampMapping:
        if self.floor == self.good:
            raise ValueError("ramp mapping anchors `floor` and `good` must differ")
        if self.log_scale and (self.floor <= 0.0 or self.good <= 0.0):
            raise ValueError(
                "log_scale ramp anchors must both be strictly positive"
            )
        return self


class BandMapping(BaseModel):
    """Maps a raw measurement onto ``[0, 1]`` where both extremes are bad.

    Zero outside ``[min_acceptable, max_acceptable]``, one across the
    ``[ideal_low, ideal_high]`` plateau, smoothstep on the two shoulders.

    The plateau matters: an image at mean luminance 120 and one at 160 are both
    simply well exposed, and ramping to a single ideal point would penalise one
    of them for no reason a photographer would recognise.
    """

    min_acceptable: float
    ideal_low: float
    ideal_high: float
    max_acceptable: float

    @model_validator(mode="after")
    def _ordered(self) -> BandMapping:
        bounds = (
            self.min_acceptable,
            self.ideal_low,
            self.ideal_high,
            self.max_acceptable,
        )
        if list(bounds) != sorted(bounds):
            raise ValueError(
                "band mapping requires "
                "min_acceptable <= ideal_low <= ideal_high <= max_acceptable"
            )
        return self


class QualityAggregationConfig(BaseModel):
    """How the component scores combine into the composite."""

    #: Power-mean exponent. 1.0 is the arithmetic mean; below 1.0 penalises low
    #: components progressively harder, so one catastrophic metric cannot be
    #: averaged away by five healthy ones.
    power: float = Field(default=0.5, gt=0.0, le=2.0)
    weights: dict[str, float] = Field(
        default_factory=lambda: {
            "blur": 0.22,
            "sharpness": 0.16,
            "brightness": 0.12,
            "contrast": 0.10,
            "noise": 0.11,
            "resolution": 0.16,
            "pixelation": 0.09,
            "distortion": 0.04,
        }
    )
    critical_floor: float = Field(default=0.12, ge=0.0, le=1.0)
    critical_components: list[str] = Field(
        default_factory=lambda: ["blur", "sharpness", "resolution"]
    )

    _COMPONENTS = (
        "blur",
        "sharpness",
        "brightness",
        "contrast",
        "noise",
        "resolution",
        "pixelation",
        "distortion",
    )

    @model_validator(mode="after")
    def _validate(self) -> QualityAggregationConfig:
        missing = [key for key in self._COMPONENTS if key not in self.weights]
        if missing:
            raise ValueError(f"quality.aggregation.weights is missing keys: {missing}")
        unknown = [key for key in self.weights if key not in self._COMPONENTS]
        if unknown:
            raise ValueError(
                f"quality.aggregation.weights has unknown keys: {unknown}"
            )
        bad_critical = [
            key for key in self.critical_components if key not in self._COMPONENTS
        ]
        if bad_critical:
            raise ValueError(
                f"quality.aggregation.critical_components has unknown keys: "
                f"{bad_critical}"
            )
        object.__setattr__(
            self, "weights", _normalised_weights(self.weights, "quality.aggregation")
        )
        return self


class RoleQualityConfig(BaseModel):
    """Per-image-role quality acceptance policy."""

    min_overall: float = Field(ge=0.0, le=100.0)

    #: Components whose critical floor is enforced *for this role*, overriding
    #: ``aggregation.critical_components``. ``None`` inherits the global list.
    #:
    #: Exists because the global list is role-blind in a way that measurement
    #: showed to be wrong. The critical floor on focus assumes softness means
    #: camera shake, which is right for a live capture. For a portrait printed
    #: at a few hundred dpi, softness is the physics of the medium: measured on
    #: a print-degraded reference face, sharpness fell to 0.00 while ArcFace
    #: still separated the same person at cosine 0.551 from an impostor at
    #: -0.028, against a CNIC threshold of 0.42. Refusing to compare that image
    #: would discard a decisive match on the grounds that it looked like what
    #: it is.
    critical_components: list[str] | None = None


class BlurConfig(BaseModel):
    """Whole-image focus measures."""

    laplacian_variance: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=40.0, good=4000.0, log_scale=True)
    )
    tenengrad: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=800.0, good=16000.0, log_scale=True)
    )
    high_frequency_ratio: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=0.0002, good=0.020, log_scale=True)
    )
    weights: dict[str, float] = Field(
        default_factory=lambda: {"laplacian": 0.35, "tenengrad": 0.30, "spectral": 0.35}
    )

    @model_validator(mode="after")
    def _normalise(self) -> BlurConfig:
        object.__setattr__(
            self, "weights", _normalised_weights(self.weights, "quality.blur")
        )
        return self


class SharpnessConfig(BaseModel):
    """Face-region focus, distinct from whole-image blur."""

    eye_region_laplacian: RampMapping = Field(
        default_factory=lambda: RampMapping(
            floor=500.0, good=20000.0, log_scale=True
        )
    )
    face_vs_scene_ratio: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=0.25, good=0.90)
    )
    weights: dict[str, float] = Field(
        default_factory=lambda: {"eye_region": 0.80, "relative": 0.20}
    )

    @model_validator(mode="after")
    def _normalise(self) -> SharpnessConfig:
        object.__setattr__(
            self, "weights", _normalised_weights(self.weights, "quality.sharpness")
        )
        return self


class BrightnessConfig(BaseModel):
    """Exposure: mean luminance plus shadow and highlight clipping."""

    mean_luma: BandMapping = Field(
        default_factory=lambda: BandMapping(
            min_acceptable=30.0,
            ideal_low=95.0,
            ideal_high=180.0,
            max_acceptable=230.0,
        )
    )
    shadow_clipping: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=0.18, good=0.01)
    )
    highlight_clipping: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=0.12, good=0.005)
    )
    #: How much of the score the clipping terms may withhold from an image
    #: that is otherwise correctly exposed. 0.45 means a well-exposed but
    #: totally clipped photograph scores 0.55 rather than 0.
    clipping_influence: float = Field(default=0.45, ge=0.0, le=1.0)
    weights: dict[str, float] = Field(
        default_factory=lambda: {"shadow_clip": 0.5, "highlight_clip": 0.5}
    )

    @model_validator(mode="after")
    def _normalise(self) -> BrightnessConfig:
        object.__setattr__(
            self, "weights", _normalised_weights(self.weights, "quality.brightness")
        )
        return self


class ContrastConfig(BaseModel):
    """Tonal separation: RMS, dynamic range and histogram entropy."""

    rms: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=10.0, good=52.0)
    )
    dynamic_range: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=45.0, good=190.0)
    )
    entropy: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=3.2, good=7.0)
    )
    weights: dict[str, float] = Field(
        default_factory=lambda: {"rms": 0.40, "dynamic_range": 0.30, "entropy": 0.30}
    )

    @model_validator(mode="after")
    def _normalise(self) -> ContrastConfig:
        object.__setattr__(
            self, "weights", _normalised_weights(self.weights, "quality.contrast")
        )
        return self


class NoiseConfig(BaseModel):
    """Sensor noise, absolute and relative to signal contrast."""

    sigma: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=15.0, good=1.5)
    )
    noise_to_signal: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=0.45, good=0.03)
    )
    weights: dict[str, float] = Field(
        default_factory=lambda: {"sigma": 0.55, "ratio": 0.45}
    )

    @model_validator(mode="after")
    def _normalise(self) -> NoiseConfig:
        object.__setattr__(
            self, "weights", _normalised_weights(self.weights, "quality.noise")
        )
        return self


class ResolutionConfig(BaseModel):
    """Genuine, as-captured resolution of the face."""

    face_short_side: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=48.0, good=150.0)
    )
    interocular: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=22.0, good=70.0)
    )
    detail_energy: RampMapping = Field(
        default_factory=lambda: RampMapping(
            floor=0.00005, good=0.005, log_scale=True
        )
    )
    weights: dict[str, float] = Field(
        default_factory=lambda: {"face_size": 0.35, "interocular": 0.25, "detail": 0.40}
    )

    @model_validator(mode="after")
    def _normalise(self) -> ResolutionConfig:
        object.__setattr__(
            self, "weights", _normalised_weights(self.weights, "quality.resolution")
        )
        return self


class PixelationConfig(BaseModel):
    """Block artefacts and inferred upscaling."""

    blockiness: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=1.30, good=0.20)
    )
    weights: dict[str, float] = Field(
        default_factory=lambda: {"blockiness": 0.45, "face_blockiness": 0.55}
    )

    @model_validator(mode="after")
    def _normalise(self) -> PixelationConfig:
        object.__setattr__(
            self, "weights", _normalised_weights(self.weights, "quality.pixelation")
        )
        return self


class DistortionConfig(BaseModel):
    """Posterisation, colour fringing and geometric anisotropy."""

    banding: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=0.35, good=0.03)
    )
    chromatic_aberration: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=14.0, good=1.5)
    )
    geometric_anisotropy: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=0.50, good=0.15)
    )
    #: Head yaw beyond which the anisotropy measurement is meaningless, because
    #: perspective foreshortening is indistinguishable from a stretched image.
    max_yaw_for_anisotropy: float = Field(default=20.0, gt=0.0, le=90.0)
    weights: dict[str, float] = Field(
        default_factory=lambda: {"banding": 0.35, "chromatic": 0.30, "geometric": 0.35}
    )

    @model_validator(mode="after")
    def _normalise(self) -> DistortionConfig:
        object.__setattr__(
            self, "weights", _normalised_weights(self.weights, "quality.distortion")
        )
        return self


class QualityConfig(BaseModel):
    """MODULE 2 - image and face quality thresholds."""

    canonical_face_size: int = Field(default=160, ge=64, le=512)
    face_crop_margin: float = Field(default=0.15, ge=0.0, le=1.0)
    global_analysis_long_side: int = Field(default=1024, ge=256)

    aggregation: QualityAggregationConfig = Field(
        default_factory=QualityAggregationConfig
    )
    roles: dict[str, RoleQualityConfig] = Field(default_factory=dict)
    default_min_overall: float = Field(default=50.0, ge=0.0, le=100.0)

    blur: BlurConfig = Field(default_factory=BlurConfig)
    sharpness: SharpnessConfig = Field(default_factory=SharpnessConfig)
    brightness: BrightnessConfig = Field(default_factory=BrightnessConfig)
    contrast: ContrastConfig = Field(default_factory=ContrastConfig)
    noise: NoiseConfig = Field(default_factory=NoiseConfig)
    resolution: ResolutionConfig = Field(default_factory=ResolutionConfig)
    pixelation: PixelationConfig = Field(default_factory=PixelationConfig)
    distortion: DistortionConfig = Field(default_factory=DistortionConfig)

    def min_overall_for(self, role: str) -> float:
        """Return the acceptance threshold for an image role.

        Args:
            role: The :class:`~hamqadam_ai.core.constants.ImageRole` value.

        Returns:
            The configured minimum composite score, falling back to
            ``default_min_overall`` for an unlisted role.
        """
        entry = self.roles.get(role)
        return entry.min_overall if entry is not None else self.default_min_overall

    def critical_components_for(self, role: str) -> list[str]:
        """Return the components whose critical floor applies to a role.

        Args:
            role: The :class:`~hamqadam_ai.core.constants.ImageRole` value.

        Returns:
            The role's override when one is configured, otherwise the global
            list from ``aggregation.critical_components``.
        """
        entry = self.roles.get(role)
        if entry is not None and entry.critical_components is not None:
            return list(entry.critical_components)
        return list(self.aggregation.critical_components)


class AlignmentConfig(BaseModel):
    """How a detected face is warped into the recogniser's input frame."""

    output_size: tuple[int, int] = (112, 112)
    max_alignment_residual: float = Field(default=0.28, gt=0.0, le=2.0)
    allow_box_fallback: bool = True
    box_fallback_margin: float = Field(default=0.10, ge=0.0, le=1.0)

    @field_validator("output_size")
    @classmethod
    def _matches_arcface(cls, value: tuple[int, int]) -> tuple[int, int]:
        """ArcFace's template is defined at 112x112 and is not resizable.

        The five reference landmark coordinates are absolute pixel positions in
        that frame, so changing the output size silently mis-places every one
        of them and quietly degrades recognition rather than failing.
        """
        if value != (112, 112):
            raise ValueError(
                "embedding.alignment.output_size must be [112, 112]: the ArcFace "
                "landmark template is defined in absolute pixels at that size."
            )
        return value


class EmbeddingBatchConfig(BaseModel):
    """How aligned crops are coalesced into forward passes."""

    max_size: int = Field(default=16, ge=1, le=128)


class EmbeddingCacheConfig(BaseModel):
    """Caching policy for computed embeddings.

    An embedding is biometric data, so the backend choice is a
    data-protection decision as much as a performance one. ``memory`` keeps
    vectors in-process behind a short TTL and they die with the pod; ``redis``
    writes them to a shared store outside this service's lifecycle.
    """

    enabled: bool = True
    backend: Literal["memory", "redis", "none"] = "memory"
    max_entries: int = Field(default=2048, ge=1)
    ttl_seconds: int = Field(default=600, gt=0)
    namespace: str = "hqai:emb"


class EmbeddingQualityConfig(BaseModel):
    """Per-embedding confidence.

    Derived from the **alignment residual**, not from the embedding magnitude.
    The magnitude was tried first, on the MagFace premise that it tracks face
    quality, and measurement refuted it for this artefact: across a twelve-step
    degradation ladder the norm varied only 22.8-25.5, and a heavily blurred
    face measured *higher* than the pristine one.
    """

    #: Mean landmark-to-template distance after warping, in interocular units.
    #: Lower is better, so the anchors are inverted. Measured range for a
    #: correctly-detected face is 0.034-0.061.
    alignment_residual: RampMapping = Field(
        default_factory=lambda: RampMapping(floor=0.25, good=0.06)
    )
    #: Confidence used when the box-only fallback ran and no residual exists.
    #: Below `min_confidence` by design, so the fallback is always flagged.
    box_fallback_confidence: float = Field(default=0.30, ge=0.0, le=1.0)
    min_confidence: float = Field(default=0.35, ge=0.0, le=1.0)


class EmbeddingConfig(BaseModel):
    """MODULE 3 - face embedding generation."""

    model: str = "face_embedder_arcface"
    dimension: int = Field(default=512, ge=64, le=2048)
    alignment: AlignmentConfig = Field(default_factory=AlignmentConfig)
    flip_augmentation: bool = False
    batch: EmbeddingBatchConfig = Field(default_factory=EmbeddingBatchConfig)
    cache: EmbeddingCacheConfig = Field(default_factory=EmbeddingCacheConfig)
    quality: EmbeddingQualityConfig = Field(default_factory=EmbeddingQualityConfig)

    model_config = {"protected_namespaces": ()}


class MatchThresholds(BaseModel):
    """Two-point operating curve for one comparison type."""

    strong_match: float = Field(ge=-1.0, le=1.0)
    review: float = Field(ge=-1.0, le=1.0)

    @model_validator(mode="after")
    def _ordered(self) -> MatchThresholds:
        if self.review >= self.strong_match:
            raise ValueError("review threshold must be strictly below strong_match")
        return self


class ScoreCalibration(BaseModel):
    """Maps a cosine similarity onto the reported 0-100 scale.

    Interpolates through the decision boundaries rather than rescaling the raw
    metric, so the reported number is meaningful relative to the operating
    point. The naive ``(cos + 1) / 2 * 100`` would report 50 for an impostor at
    cosine zero, which reads as "half a match" and is the opposite of the truth.
    """

    strong_match_score: float = Field(default=75.0, gt=0.0, le=100.0)
    review_score: float = Field(default=50.0, gt=0.0, le=100.0)
    floor_similarity: float = Field(default=0.0, ge=-1.0, lt=1.0)

    @model_validator(mode="after")
    def _ordered(self) -> ScoreCalibration:
        if self.review_score >= self.strong_match_score:
            raise ValueError(
                "matching.calibration.review_score must be below strong_match_score"
            )
        return self


class MatchConfidenceConfig(BaseModel):
    """How embedding confidence propagates into a comparison."""

    #: A comparison is only as trustworthy as its weaker embedding, so the pair
    #: takes the minimum rather than the mean of the two confidences.
    min_pair_confidence: float = Field(default=0.35, ge=0.0, le=1.0)
    #: Weight a low-confidence comparison carries in aggregation. Not zero -
    #: the evidence is degraded, not absent.
    low_confidence_weight: float = Field(default=0.40, ge=0.0, le=1.0)


class IdentityAggregationConfig(BaseModel):
    """How individual comparisons combine into one identity confidence."""

    weights: dict[str, float] = Field(
        default_factory=lambda: {"cnic": 0.45, "profile": 0.35, "secondary": 0.20}
    )
    secondary_aggregation: Literal["mean", "max", "min"] = "mean"
    cnic_failure_cap: float = Field(default=45.0, ge=0.0, le=100.0)
    min_comparisons: int = Field(default=1, ge=1)

    _REQUIRED = ("cnic", "profile", "secondary")

    @model_validator(mode="after")
    def _validate(self) -> IdentityAggregationConfig:
        missing = [key for key in self._REQUIRED if key not in self.weights]
        if missing:
            raise ValueError(
                f"matching.identity.weights is missing keys: {missing}"
            )
        unknown = [key for key in self.weights if key not in self._REQUIRED]
        if unknown:
            raise ValueError(
                f"matching.identity.weights has unknown keys: {unknown}"
            )
        object.__setattr__(
            self, "weights", _normalised_weights(self.weights, "matching.identity")
        )
        return self


class MatchingConfig(BaseModel):
    """MODULE 4 - face-matching operating points."""

    selfie_vs_profile: MatchThresholds = Field(
        default_factory=lambda: MatchThresholds(strong_match=0.62, review=0.45)
    )
    selfie_vs_secondary: MatchThresholds = Field(
        default_factory=lambda: MatchThresholds(strong_match=0.60, review=0.43)
    )
    selfie_vs_cnic: MatchThresholds = Field(
        default_factory=lambda: MatchThresholds(strong_match=0.42, review=0.30)
    )
    calibration: ScoreCalibration = Field(default_factory=ScoreCalibration)
    confidence: MatchConfidenceConfig = Field(default_factory=MatchConfidenceConfig)
    identity: IdentityAggregationConfig = Field(
        default_factory=IdentityAggregationConfig
    )

    def thresholds_for(self, comparison: str) -> MatchThresholds:
        """Return the operating points for a comparison type.

        Args:
            comparison: ``profile``, ``secondary`` or ``cnic``.

        Raises:
            ValueError: for an unknown comparison type.
        """
        mapping = {
            "profile": self.selfie_vs_profile,
            "secondary": self.selfie_vs_secondary,
            "cnic": self.selfie_vs_cnic,
        }
        try:
            return mapping[comparison]
        except KeyError as exc:
            raise ValueError(
                f"Unknown comparison type {comparison!r}; "
                f"expected one of {sorted(mapping)}"
            ) from exc


class OcrPreprocessingConfig(BaseModel):
    """Getting a photographed card into a readable state."""

    rectify: bool = True
    min_card_coverage: float = Field(default=0.12, gt=0.0, le=1.0)
    aspect_tolerance: float = Field(default=0.35, gt=0.0, le=1.0)
    deskew: bool = True
    enhance: bool = True
    clahe_clip_limit: float = Field(default=2.5, gt=0.0, le=10.0)
    min_width: int = Field(default=700, ge=200)


class OcrOrientationConfig(BaseModel):
    """Resolving which way up the card is."""

    enabled: bool = True
    early_exit: bool = True
    min_lines_for_acceptance: int = Field(default=6, ge=1)
    max_attempts: int = Field(default=4, ge=1, le=4)


class OcrConfig(BaseModel):
    """MODULE 5 - CNIC OCR."""

    engine_chain: list[str] = Field(
        default_factory=lambda: ["onnx_ppocr", "paddleocr", "easyocr"]
    )
    language: str = "en"
    use_angle_classifier: bool = True
    min_line_confidence: float = Field(default=0.35, ge=0.0, le=1.0)
    #: Acceptance floor for detection-free crop recognition. Much lower
    #: than the full-page floor because the scores are not comparable: an
    #: isolated glyph measured 0.24 where the same character inside a line
    #: scores above 0.8.
    min_crop_confidence: float = Field(default=0.12, ge=0.0, le=1.0)

    preprocessing: OcrPreprocessingConfig = Field(
        default_factory=OcrPreprocessingConfig
    )
    orientation: OcrOrientationConfig = Field(default_factory=OcrOrientationConfig)

    min_confidence: float = Field(default=0.70, ge=0.0, le=1.0)
    min_required_fields: int = Field(default=4, ge=0)

    field_weights: dict[str, float] = Field(
        default_factory=lambda: {
            "cnic_number": 0.30,
            "full_name": 0.20,
            "date_of_birth": 0.18,
            "gender": 0.12,
            "date_of_issue": 0.10,
            "date_of_expiry": 0.10,
        }
    )

    _KNOWN_ENGINES = ("onnx_ppocr", "paddleocr", "easyocr")

    @model_validator(mode="after")
    def _validate(self) -> OcrConfig:
        unknown = [name for name in self.engine_chain if name not in self._KNOWN_ENGINES]
        if unknown:
            raise ValueError(
                f"ocr.engine_chain references unknown engines: {unknown}; "
                f"supported are {list(self._KNOWN_ENGINES)}"
            )
        if not self.engine_chain:
            raise ValueError("ocr.engine_chain must name at least one engine")
        object.__setattr__(
            self, "field_weights", _normalised_weights(self.field_weights, "ocr")
        )
        return self


class ScreenshotDetectorConfig(BaseModel):
    """MODULE 7 - is this a screenshot of an application?

    Anchors bracket the empty gap between two measured populations. Interior
    constant-row fraction, after contiguous edge padding is stripped:

        genuine photograph            0.000
        quality-12 JPEG               0.000
        letterboxed photograph        0.000
        square-padded then JPEG       0.000
        photograph of a print         0.000
        screenshot                    0.175 - 0.187
    """

    #: Below this the reading counts as no evidence at all.
    interior_rows_floor: float = Field(default=0.04, ge=0.0, le=1.0)
    #: At or above this the reading is as strong as it gets.
    interior_rows_ceiling: float = Field(default=0.15, ge=0.0, le=1.0)
    #: Confidence at which the finding is reported as triggered.
    min_confidence: float = Field(default=0.55, ge=0.0, le=1.0)


class MoireDetectorConfig(BaseModel):
    """MODULE 7 - is this a photograph of a screen?

    Peak prominence above the locally-smoothed log spectrum:

        everything that is not a screen capture   1.410 - 1.456
        photograph of a screen                    3.461 - 4.220
    """

    #: Inner edge of the search annulus, as a fraction of the spectrum size.
    #: Inside this sits the DC neighbourhood, where every image has energy.
    min_radius_fraction: float = Field(default=0.06, gt=0.0, lt=0.5)
    #: Outer edge. Beyond it the resample's own filter has removed everything.
    max_radius_fraction: float = Field(default=0.48, gt=0.0, le=0.5)
    #: Half-width of the excluded band along each axis, in spectrum pixels.
    #: JPEG's 8x8 blocking puts a comb of energy exactly on the axes.
    axis_exclusion: int = Field(default=6, ge=0, le=64)
    #: Gaussian sigma used to estimate the smooth background to subtract.
    background_sigma: float = Field(default=9.0, gt=0.0, le=64.0)

    prominence_floor: float = Field(default=1.90, ge=0.0)
    prominence_ceiling: float = Field(default=3.20, ge=0.0)
    min_confidence: float = Field(default=0.55, ge=0.0, le=1.0)


class PrintRecaptureDetectorConfig(BaseModel):
    """MODULE 7 - is this a photograph of a printed photograph?

    Share of spectral power above half Nyquist:

        twice-recompressed            0.0206
        genuine photograph            0.0178
        quality-12 JPEG               0.0121
        photograph of a print         0.0021
    """

    #: Anchors run downwards: less high-frequency content is more print-like.
    high_frequency_floor: float = Field(default=0.0090, ge=0.0, le=1.0)
    high_frequency_ceiling: float = Field(default=0.0030, ge=0.0, le=1.0)
    #: Corroboration. Ink reaches neither true black nor paper white, so the
    #: 2nd-to-98th percentile span is compressed. Also runs downwards.
    tonal_span_floor: float = Field(default=0.90, ge=0.0, le=1.0)
    tonal_span_ceiling: float = Field(default=0.60, ge=0.0, le=1.0)
    min_confidence: float = Field(default=0.55, ge=0.0, le=1.0)


class SyntheticDetectorConfig(BaseModel):
    """MODULE 7 - is this rendered artwork rather than a photograph?

    Distinct colours per sampled pixel, and flat-block share:

                                  palette   flat blocks
        genuine photograph          0.286         0.000
        quality-12 JPEG             0.173         0.355
        screenshot                  0.235         0.359
        synthetic render            0.000         0.911

    Both must agree. A small palette alone fires on a posterised photograph; a
    high flat share alone fires on the quality-12 JPEG.
    """

    #: Anchors run downwards: fewer distinct colours is more synthetic.
    palette_floor: float = Field(default=0.090, ge=0.0, le=1.0)
    palette_ceiling: float = Field(default=0.010, ge=0.0, le=1.0)
    flat_floor: float = Field(default=0.50, ge=0.0, le=1.0)
    flat_ceiling: float = Field(default=0.85, ge=0.0, le=1.0)
    #: Pixels sampled when counting distinct colours.
    colour_sample_size: int = Field(default=200_000, ge=1_000)
    min_confidence: float = Field(default=0.55, ge=0.0, le=1.0)


class ProfileAnalysisConfig(BaseModel):
    """MODULE 7 - profile image analysis."""

    screenshot: ScreenshotDetectorConfig = Field(
        default_factory=ScreenshotDetectorConfig
    )
    moire: MoireDetectorConfig = Field(default_factory=MoireDetectorConfig)
    print_recapture: PrintRecaptureDetectorConfig = Field(
        default_factory=PrintRecaptureDetectorConfig
    )
    synthetic: SyntheticDetectorConfig = Field(
        default_factory=SyntheticDetectorConfig
    )

    #: Authenticity score below which the image is reported as probably not a
    #: genuine capture of the uploader. A recommendation to the rules engine,
    #: never a rejection made here.
    min_authenticity_score: float = Field(default=55.0, ge=0.0, le=100.0)

    #: Require a detectable face in a profile photograph. A profile picture
    #: with no person in it is not a fraud signal - it is a user who uploaded
    #: their cat - but it cannot be verified against a selfie either.
    require_face: bool = True

    #: Treat more than one qualifying face as a finding. A group photograph is
    #: ambiguous about which person the account belongs to.
    flag_multiple_faces: bool = True


class CnicPortraitGeometry(BaseModel):
    """Where the portrait sits on an ID-1 card, and how big it may be.

    These are **priors used to validate and rank** detected faces, never to
    blind-crop. Template revisions move the photo box, and a prior that
    silently overrode the detector would fail closed on a card layout nobody
    anticipated.

    The area bounds are the load-bearing part. They come from physical
    proportion rather than from any dataset: an ID-1 card is 85.6 x 53.98 mm
    and its photo box is a fixed physical size, so the face inside that box
    occupies a bounded fraction of the card *whatever* resolution the card was
    photographed at. That makes the bound a geometric fact about the document,
    not a tuned heuristic - and it is what rejects a live face filling half the
    frame.
    """

    #: Horizontal bands, as fractions of card width, where the photo box may
    #: begin and end. Both sides are listed because the layout has moved
    #: between CNIC generations and this module refuses to assert one.
    candidate_bands: list[tuple[float, float]] = Field(
        default_factory=lambda: [(0.00, 0.38), (0.62, 1.00)]
    )
    #: Vertical extent of the photo box, as fractions of card height.
    vertical_band: tuple[float, float] = (0.10, 0.95)
    #: Smallest face, in pixels of the shorter side, in the image actually
    #: searched.
    #:
    #: A **pixel count, not a ratio**, and the distinction matters. Whether a
    #: face can be recognised depends on how many pixels it has, not on what
    #: fraction of the frame it covers - a ratio floor conflates "this is not a
    #: face" with "the card was photographed small", and rejects the genuine
    #: portrait on any card that does not fill the frame. Guarding against
    #: detector hallucinations is what ``min_detector_confidence`` is for.
    #:
    #: 40 px because ArcFace resamples to 112 x 112: below roughly that, the
    #: upscale is pure interpolation and adds nothing the network can use.
    #: Lower than Module 1's live-image floor of 64, deliberately - a printed
    #: portrait is small and there is no retaking it larger.
    min_face_pixels: int = Field(default=40, ge=8, le=512)
    #: Largest share, derived from physical proportion rather than tuned. An
    #: ID-1 card is 4620 mm^2; a generous photo box is 30 x 40 mm, and the face
    #: inside a passport-style portrait occupies roughly a third of that box -
    #: so about 10% of the card, at the very top of the plausible range.
    #:
    #: Measured for comparison: the reference synthetic card's printed portrait
    #: gives a face area ratio of **0.0125**, and the live face in the
    #: held-in-front-of-the-camera attack gives **0.183**. The bound sits an
    #: order of magnitude above the genuine case and well below the attack.
    max_face_area_ratio: float = Field(default=0.10, gt=0.0, le=1.0)
    #: How far outside a candidate band a face centre may stray before it is
    #: treated as off-template rather than merely off-centre.
    band_tolerance: float = Field(default=0.08, ge=0.0, le=0.5)


class CnicFaceConfig(BaseModel):
    """MODULE 6 - locating the CNIC portrait and matching it to the selfie."""

    #: Rectify the card before looking for the portrait. The primary defence
    #: against a face held behind the card: warping to the card's own bounds
    #: removes everything that is not on it.
    rectify_first: bool = True
    #: Fall back to searching the unrectified frame when no card quadrilateral
    #: was found. Correct - a flat scan has no border to find - but the result
    #: is flagged, because the geometric containment guarantee is then absent.
    allow_unrectified: bool = True
    #: Minimum width the card is upscaled to before detection. The portrait is
    #: a small, low-DPI print; the detector needs pixels more than it needs
    #: speed here.
    detection_min_width: int = Field(default=1200, ge=320, le=4096)
    #: Detector confidence floor for a portrait candidate. Below the live-image
    #: floor on purpose: a laminated sub-300-dpi print photographed through
    #: glare is a genuinely harder detection than a selfie, and holding it to
    #: the selfie bar loses real portraits.
    min_detector_confidence: float = Field(default=0.35, ge=0.0, le=1.0)
    #: There is deliberately no portrait-quality threshold here. Whether a
    #: located portrait is good enough to embed is decided by
    #: ``quality.roles.cnic_portrait`` - its composite floor and its critical
    #: components - and duplicating that number in this section would give two
    #: places to change one policy.
    geometry: CnicPortraitGeometry = Field(default_factory=CnicPortraitGeometry)


class QdrantConfig(BaseModel):
    """Connection settings for the durable gallery."""

    #: Endpoint. ``:memory:`` or a filesystem path use the client's embedded
    #: engine instead of HTTP - useful for a single node and for tests.
    url: str = "http://localhost:6333"
    collection: str = "hamqadam_faces"
    api_key: str | None = None
    timeout_seconds: float = Field(default=5.0, gt=0.0, le=120.0)
    #: Create the collection when absent. A locked-down environment can turn
    #: this off and provision it out of band.
    create_collection: bool = True


class DuplicateConfig(BaseModel):
    """MODULE 8 - duplicate-face search.

    The thresholds here are **not validated**, and the module says so in every
    response. A 1:N search is not a 1:1 verification: its false-match rate
    compounds with gallery size, and simulation puts the correct threshold
    anywhere between 0.26 and 0.96 depending on a property of the embedding
    manifold that cannot be measured without a real gallery. See
    :mod:`hamqadam_ai.duplicate_detection.calibration`.
    """

    #: Which gallery adapter to use. ``memory`` is exact and fast and loses
    #: everything on restart; ``qdrant`` is durable and shared.
    backend: Literal["memory", "qdrant"] = "memory"
    qdrant: QdrantConfig = Field(default_factory=QdrantConfig)
    #: Ceiling on the in-process gallery. A guard against an unbounded leak,
    #: not a policy - evicting silently would silently stop detecting
    #: duplicates of long-standing users.
    max_memory_records: int = Field(default=250_000, ge=1)

    similarity_threshold: float = Field(default=0.68, ge=-1.0, le=1.0)
    review_threshold: float = Field(default=0.58, ge=-1.0, le=1.0)
    top_k: int = Field(default=10, ge=1, le=100)
    on_duplicate: Literal["manual_review", "reject"] = "manual_review"

    @model_validator(mode="after")
    def _validate(self) -> DuplicateConfig:
        if self.review_threshold > self.similarity_threshold:
            raise ValueError(
                "duplicate.review_threshold must not exceed "
                "duplicate.similarity_threshold; a hit cannot need review at a "
                "similarity that already counts as a duplicate"
            )
        return self


class FraudLevels(BaseModel):
    """Boundaries of the LOW / MEDIUM / HIGH risk bands, on a 0-100 scale."""

    low_max: float = Field(default=30.0, ge=0, le=100)
    medium_max: float = Field(default=65.0, ge=0, le=100)

    @model_validator(mode="after")
    def _ordered(self) -> FraudLevels:
        if self.low_max >= self.medium_max:
            raise ValueError("fraud.levels.low_max must be < medium_max")
        return self


class FraudConfig(BaseModel):
    """MODULE 9 - fraud risk aggregation and banding.

    The weights here are **policy, not measurement**. There is no labelled
    fraud data in this project, so nothing below is calibrated; the response
    reports ``weights_validated: false`` so a reader cannot mistake a
    defensible default for a derived one.
    """

    levels: FraudLevels = Field(default_factory=FraudLevels)

    #: Ceilings on how far one kind of evidence can push the score by itself,
    #: keyed by signal family. A family without an entry is uncapped.
    #:
    #: Capture quality is capped hard and deliberately. Most bad photographs
    #: are just bad photographs, and an engine that reads blur as dishonesty
    #: will reject honest users all day. Measured on the aggregation itself:
    #: four quality sub-findings summed additively reach 65, the boundary of
    #: HIGH risk, for an ordinary out-of-focus snapshot.
    family_caps: dict[str, float] = Field(
        default_factory=lambda: {
            "capture_quality": 0.25,
            "presentation": 0.60,
        }
    )

    #: Per-code weight overrides, so the policy can be retuned without a code
    #: change. Codes and their defaults are in
    #: :mod:`hamqadam_ai.fraud_detection.signals`.
    signal_weights: dict[str, float] = Field(default_factory=dict)

    #: How many checks a full request is expected to run. Used only to derive
    #: ``assessment_confidence``: the share of intended evidence that was
    #: actually available.
    expected_checks: int = Field(default=6, ge=1, le=32)

    @model_validator(mode="after")
    def _validate(self) -> FraudConfig:
        for family, cap in self.family_caps.items():
            if not 0.0 <= cap <= 1.0:
                raise ValueError(
                    f"fraud.family_caps[{family!r}] must lie in [0, 1], got {cap}"
                )
        for code, weight in self.signal_weights.items():
            if not 0.0 <= weight <= 1.0:
                raise ValueError(
                    f"fraud.signal_weights[{code!r}] must lie in [0, 1], got {weight}"
                )
        return self


class ApproveRule(BaseModel):
    """Conditions all of which must hold for an automatic APPROVE."""

    min_identity_confidence: float = Field(default=75.0, ge=0, le=100)
    max_fraud_risk: float = Field(default=30.0, ge=0, le=100)

    #: How much of the intended evidence must actually have been gathered.
    #:
    #: Without this the engine approves on whatever ran. Measured on the
    #: pipeline: a request with no CNIC at all scored identity 100.0 and fraud
    #: 0.0 - both true, both meaningless, because the document was never
    #: examined - and was recommended for automatic approval on an
    #: ``assessment_confidence`` of **0.17**.
    #:
    #: A low fraud score from checks that did not run is not a clean bill of
    #: health, and the fraud engine deliberately refuses to treat an absence as
    #: innocence. That refusal is worth nothing if the decision engine then
    #: treats the resulting zero as a pass.
    min_assessment_confidence: float = Field(default=0.70, ge=0.0, le=1.0)


class RejectRule(BaseModel):
    """Conditions any of which triggers an automatic REJECT."""

    max_identity_confidence: float = Field(default=40.0, ge=0, le=100)
    min_fraud_risk: float = Field(default=65.0, ge=0, le=100)


class DecisionConfig(BaseModel):
    """MODULE 10 - final recommendation rules."""

    approve: ApproveRule = Field(default_factory=ApproveRule)
    reject: RejectRule = Field(default_factory=RejectRule)


# --------------------------------------------------------------------------- #
# Root settings object
# --------------------------------------------------------------------------- #


class Settings(BaseSettings):
    """The complete, validated configuration of the AI verification service."""

    model_config = SettingsConfigDict(
        env_prefix="HQ_",
        env_nested_delimiter="__",
        env_file=str(REPO_ROOT / ".env"),
        env_file_encoding="utf-8",
        extra="ignore",
        case_sensitive=False,
        protected_namespaces=(),
        validate_default=True,
    )

    app: AppConfig = Field(default_factory=AppConfig)
    server: ServerConfig = Field(default_factory=ServerConfig)
    security: SecurityConfig = Field(default_factory=SecurityConfig)
    storage: StorageConfig = Field(default_factory=StorageConfig)
    runtime: RuntimeConfig = Field(default_factory=RuntimeConfig)
    observability: ObservabilityConfig = Field(default_factory=ObservabilityConfig)
    logging: LoggingConfig = Field(default_factory=LoggingConfig)

    model_store: ModelStoreConfig = Field(default_factory=ModelStoreConfig)
    models: dict[str, ModelSpec] = Field(default_factory=dict)
    execution_providers: dict[str, list[ProviderSpec]] = Field(default_factory=dict)

    detection: DetectionConfig = Field(default_factory=DetectionConfig)
    quality: QualityConfig = Field(default_factory=QualityConfig)
    embedding: EmbeddingConfig = Field(default_factory=EmbeddingConfig)
    matching: MatchingConfig = Field(default_factory=MatchingConfig)
    ocr: OcrConfig = Field(default_factory=OcrConfig)
    cnic_face: CnicFaceConfig = Field(default_factory=CnicFaceConfig)
    profile: ProfileAnalysisConfig = Field(
        default_factory=ProfileAnalysisConfig
    )
    duplicate: DuplicateConfig = Field(default_factory=DuplicateConfig)
    fraud: FraudConfig = Field(default_factory=FraudConfig)
    decision: DecisionConfig = Field(default_factory=DecisionConfig)

    #: Populated by the YAML source; useful in diagnostics and health output.
    config_dir_: str | None = Field(default=None, alias="_config_dir")

    # -- Source ordering ------------------------------------------------- #

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> tuple[PydanticBaseSettingsSource, ...]:
        """Highest precedence first: init kwargs > env > .env > YAML > secrets."""
        return (
            init_settings,
            env_settings,
            dotenv_settings,
            _YamlSettingsSource(settings_cls),
            file_secret_settings,
        )

    # -- Cross-section invariants ---------------------------------------- #

    @model_validator(mode="after")
    def _validate_production_hardening(self) -> Settings:
        """Refuse to serve production traffic with development-grade settings."""
        if not (self.app.is_production and self.security.enforce_production_hardening):
            return self

        problems: list[str] = []
        if self.app.debug:
            problems.append("app.debug must be false in production")
        if self.security.require_api_key and not self.security.api_keys:
            problems.append("security.api_keys is empty while require_api_key is true")
        if not self.security.require_api_key:
            problems.append("security.require_api_key must be true in production")
        if "*" in self.server.cors.allow_origins:
            problems.append("server.cors.allow_origins must not contain '*' in production")
        if self.logging.renderer != "json":
            problems.append("logging.renderer must be 'json' in production")
        if not self.logging.redaction.enabled:
            problems.append("logging.redaction.enabled must be true in production")
        if not self.model_store.verify_checksum:
            problems.append("model_store.verify_checksum must be true in production")

        if problems:
            raise ConfigurationError(
                "Production hardening checks failed.",
                details={"problems": problems},
            )
        return self

    @model_validator(mode="after")
    def _validate_detector_chain(self) -> Settings:
        """Every detector in the chain must resolve to a declared model."""
        known = {
            "scrfd": "face_detector_scrfd",
            "yolo": "face_detector_yolo",
            "opencv_dnn": "face_detector_opencv_dnn",
            "haar": "face_detector_haar",
        }
        unknown = [name for name in self.detection.fallback_chain if name not in known]
        if unknown:
            raise ConfigurationError(
                f"detection.fallback_chain references unknown detectors: {unknown}",
                details={"unknown": unknown, "supported": sorted(known)},
            )
        # `models` is empty when Settings is built without YAML (unit tests);
        # only enforce the cross-reference when a registry is actually present.
        if self.models:
            missing = [
                known[name]
                for name in self.detection.fallback_chain
                if known[name] not in self.models
            ]
            if missing:
                raise ConfigurationError(
                    f"detection.fallback_chain requires models absent from models.yaml: {missing}",
                    details={"missing": missing},
                )
        return self

    # -- Helpers ---------------------------------------------------------- #

    def model_spec(self, key: str) -> ModelSpec:
        """Return the :class:`ModelSpec` registered under ``key``.

        Raises:
            ConfigurationError: if no such model is declared.
        """
        try:
            return self.models[key]
        except KeyError as exc:
            raise ConfigurationError(
                f"No model named {key!r} is declared in models.yaml.",
                details={"requested": key, "available": sorted(self.models)},
            ) from exc

    def providers_for(self, device: str) -> Sequence[ProviderSpec]:
        """Return the execution-provider preference list for a device family."""
        return self.execution_providers.get(
            device, [ProviderSpec(name="CPUExecutionProvider")]
        )

    def model_version_map(self) -> dict[str, str]:
        """Map of model key to version string, for the API's ``model_versions``."""
        return {key: spec.version for key, spec in self.models.items() if spec.enabled}


# --------------------------------------------------------------------------- #
# Accessors
# --------------------------------------------------------------------------- #


#: Process-wide singleton. Configuration is immutable for the lifetime of a
#: process, so it is built once and shared. Guarded by a lock because the
#: FastAPI lifespan hook and a background janitor may race on first access.
_settings_singleton: Settings | None = None
_settings_lock = threading.Lock()


def get_settings() -> Settings:
    """Return the process-wide settings singleton, building it on first use.

    Raises:
        ConfigurationError: if the configuration fails validation. Pydantic's
            own ``ValidationError`` is wrapped so callers only ever have to
            catch :class:`~hamqadam_ai.core.exceptions.HamqadamError`.
    """
    global _settings_singleton
    if _settings_singleton is not None:
        return _settings_singleton
    with _settings_lock:
        if _settings_singleton is None:
            _settings_singleton = _build_settings()
    return _settings_singleton


def reload_settings(**overrides: Any) -> Settings:
    """Rebuild the singleton from disk, applying ``overrides`` at top precedence.

    Intended for tests and for the ``scripts/`` entry points, which need to
    point the service at a different config directory or flip one threshold
    without editing YAML.

    Args:
        **overrides: Init kwargs forwarded to :class:`Settings`; they outrank
            environment variables and every YAML layer.

    Returns:
        The freshly built settings object, which is also installed as the new
        process-wide singleton.
    """
    global _settings_singleton
    with _settings_lock:
        _settings_singleton = _build_settings(**overrides)
    return _settings_singleton


def _build_settings(**overrides: Any) -> Settings:
    """Instantiate :class:`Settings`, normalising validation failures."""
    try:
        return Settings(**overrides)
    except ConfigurationError:
        raise
    except ValidationError as exc:
        raise ConfigurationError(
            "Service configuration failed validation.",
            details={
                "errors": [
                    {
                        "location": ".".join(str(part) for part in error["loc"]),
                        "problem": error["msg"],
                    }
                    for error in exc.errors()
                ]
            },
            cause=exc,
        ) from exc


__all__ = [
    "REPO_ROOT",
    "AppConfig",
    "AlignmentConfig",
    "DecisionConfig",
    "DetectionConfig",
    "DetectionPolicyConfig",
    "DuplicateConfig",
    "EmbeddingCacheConfig",
    "EmbeddingConfig",
    "FraudConfig",
    "LoggingConfig",
    "MatchingConfig",
    "IdentityAggregationConfig",
    "MatchThresholds",
    "MatchConfidenceConfig",
    "ModelInputSpec",
    "ModelSpec",
    "ModelStoreConfig",
    "BandMapping",
    "ObservabilityConfig",
    "OcclusionConfig",
    "OcrConfig",
    "OcrOrientationConfig",
    "OcrPreprocessingConfig",
    "PoseConfig",
    "ProviderSpec",
    "QualityAggregationConfig",
    "QualityConfig",
    "RampMapping",
    "RoleQualityConfig",
    "RuntimeConfig",
    "ScoreCalibration",
    "SecurityConfig",
    "ServerConfig",
    "Settings",
    "StorageConfig",
    "VisibilityConfig",
    "get_settings",
    "reload_settings",
    "resolve_config_dir",
]
